djangocourse/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('dashboard.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^works/', include('works.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login$', views.login_view, name='login_view'),
    url(r'^logout$', views.logout_view, name='logout_view'),
    url(r'^profile$', views.change_profile, name='change_profile'),
]

users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class UserProfile(models.Model):
    STUDENT = 'ST'
    SUPERVISOR = 'SV'
    USER_TYPES = [(STUDENT, 'Student'),
                  (SUPERVISOR, 'Supervisor')]

    user = models.OneToOneField(User, related_name='user_profile')
    type = models.CharField(choices=USER_TYPES, max_length=2, default=STUDENT)
    first_name = models.CharField(max_length=50, default='')
    last_name = models.CharField(max_length=50, default='')
    avatar = models.ImageField(upload_to='avatars', blank=True, default='avatars/default_avatar.png')

    def __str__(self):
        if self.first_name or self.last_name:
            return '%s %s' % (self.first_name, self.last_name)
        else:
            return str(self.pk)


@receiver(post_save, sender=User)
def create_catalog(sender, instance, *args, **kwargs):
    UserProfile.objects.get_or_create(user=instance)

templates/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <title>Unarea Science</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static "/static/css/selectize/selectize.css" %}" />
    <link rel="stylesheet" href="{% static "/static/css/main.css" %}">
    {% block css %}
    {% endblock %}
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Unarea Science</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Vacant <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {% if user.is_authenticated and user.user_profile.type == 'SV' %}
                            <li><a href="#" data-toggle="modal" data-target="#vacantTopicModal">Add Vacant Topic</a></li>
                        {% endif %}
                        <li><a href="/works/vacant_topics_list">Vacant Topics</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if not user.is_authenticated %}
                    <li><a href="#" data-toggle="modal" data-target="#loginModal">Login</a></li>
                {% else %}
                    <li><a href="#" data-toggle="modal" data-target="#profileModal">Profile</a></li>
                    <li><a href="{% url 'logout_view' %}">Logout</a></li>
                {% endif %}
                {% if user.is_superuser %}
                    <li><a href="/admin">Admin</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% if messages %}
    {% for message in messages %}
        <div class="alert
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}alert-danger{% endif %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}alert-warning{% endif %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}alert-success{% endif %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}alert-info{% endif %}" role="alert">
            <a href="#" class="alert-link">{{ message }}</a>
            <a href="#" onclick="$(this).parent().fadeOut()">
                <span class="pull-right glyphicon glyphicon-remove" aria-hidden="true"></span>
            </a>
        </div>
    {% endfor %}
{% endif %}

{% if not user.is_authenticated %}
    <div class="modal fade" id="loginModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Log In:</h4>
                </div>
                <div class="modal-body">
                    <form role="form" action="{% url 'login_view' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username:</label>
                            <input type="text" class="form-control" id="username" name="username">
                        </div>
                        <div class="form-group">
                            <label for="pwd">Password:</label>
                            <input type="password" class="form-control" id="pwd" name="password">
                        </div>
                        <div class="checkbox">
                            <label><input type="checkbox"> Remember me</label>
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% else %}
    <div class="modal fade" id="profileModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Profile settings</h4>
                </div>
                <div class="modal-body">
                    <form enctype="multipart/form-data" role="form" action="{% url 'change_profile' %}" method="post">
                        <div class="row">
                            <div class="col-md-4">
                                <a href="#" class="thumbnail">
                                    <img src="/media/{{ user.user_profile.avatar }}" alt="Profile avatar">
                                </a>
                                <input type="file" name="avatar">
                            </div>
                            <div class="col-md-8">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="type">You are:</label>
                                    <input type="text" class="form-control" id="type" name="type" value="{{ user.user_profile.get_type_display }}" disabled>
                                </div>
                                <div class="form-group">
                                    <label for="first_name">First name:</label>
                                    <input type="text" class="form-control" id="first_name" name="first_name" value="{{ user.user_profile.first_name }}">
                                </div>
                                <div class="form-group">
                                    <label for="last_name">Last name:</label>
                                    <input type="text" class="form-control" id="last_name" name="last_name" value="{{ user.user_profile.last_name }}">
                                </div>
                                <button type="submit" class="btn btn-default pull-right">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% if user.user_profile.type == 'SV' %}
        <div class="modal fade" id="vacantTopicModal" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Add Vacant Topic:</h4>
                    </div>
                    <div class="modal-body">
                        <form role="form" action="{% url 'add_vacant_topic' %}" method="POST" id="vacant-topic-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="subject">Subject:</label>
                                <input type="text" class="form-control" id="subject" name="subject">
                            </div>
                            <div class="form-group">
                                <label for="year">Year of study:</label>
                                <input type="number" class="form-control" id="year" name="year">
                            </div>
                            <div class="form-group">
                                <label for="annotation">Annotation:</label>
                                <textarea class="form-control" id="annotation" name="annotation"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="annotation">For:</label>
                                <select id="select-vacant-student" name="for_student"></select>
                            </div>
                            <button type="button" class="btn btn-default" onclick="add_vacant_topic()">Add</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endif %}

{% block body %}
{% endblock %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{% static "/static/js/selectize/standalone/selectize.js" %}"></script>
{% if user.is_authenticated and user.user_profile.type == 'SV' %}
    <script>
        function add_vacant_topic(){
            var add_vacant_topic_form = $('#vacant-topic-form');
            add_vacant_topic_form.find('.form-control').each(function(){
                $(this).parent().removeClass('has-error');
                add_vacant_topic_form.find('p[class="text-danger"]').text('');
            });
            $.ajax({
                url: '{% url 'add_vacant_topic' %}',
                method: 'POST',
                data: add_vacant_topic_form.serialize(),
                success: function(data){
                    if (data.valid){
                        window.location.reload();
                    }
                    else{
                        for (var k in data.errors){
                            add_vacant_topic_form.find('input[name=' + k + ']').parent().addClass('has-error');
                            add_vacant_topic_form.find('textarea[name=' + k + ']').parent().addClass('has-error');
                        }
                        $('#vacant-topic-form-message').text(data.message);
                    }
                }
            });
        }

        $('#select-vacant-student').selectize({
            valueField: 'id',
            labelField: 'name',
            searchField: 'name',
            options: [],
            create: false,
            render: {
                option: function(item, escape) {
                    return '<div>' +
                        '<span class="title">' +
                            '<span class="name">' + escape(item.name) + '</span>' +
                        '</span>' +
                    '</div>';
                }
            },
            load: function(query, callback) {
                if (!query.length) return callback();
                $.ajax({
                    url: '{% url "vacant_students" %}',
                    type: 'GET',
                    dataType: 'json',
                    data: {
                        q: query
                    },
                    error: function() {
                        callback();
                    },
                    success: function(res) {
                        console.log(res.response);
                        callback(res.response);
                    }
                });
            }
        });
    </script>
{% endif %}
{% block js_body %}
{% endblock %}

</body>
</html>